---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr.yaml
  - jellyfin.yaml
  - jellyseer.yaml
  - media.yaml
  - prowlarr.yaml
  - radarr.yaml
  - sonarr.yaml
  - transmission.yaml

